# Site wide configuration

title: "Robot Cognition Laboratory"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
logo: logo-120.png # 120x120 px default image used for Twitter summary card
teaser: logo-400x250.png # 400x250 px default teaser image used in image archive grid
locale: en
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: "_projects"
    values:
      layout: "project"
      permalink: /projects/:title
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title

# Site owner
owner:
  name: Robot Cognition Laboratory
  email: contact@robotcog.org
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: unknow.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
